
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://henryng24.github.com"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /henryng24.github.com
# Google tracking id to track your visitors

google-tracking-id: "UA-76494877-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "HENRYNG.CO"
title: "Henry Ng"
description: "Blog and website of Henry Ng, a blog to help others."
keywords: "henry, ng, canada, canadian, software, engineer, visa, work, change, education, solar, help, mentor, solarcity, hack reactor, experience"
favicon: "/img/author.png"

################
# Header layout #
################

#black-favicon: "/img/author.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "When we long for a life without difficulties, remind us that oaks grow strong in contrary winds and diamonds were made under pressure."
  - text: "When you're having a bad day, try doing something nice for someone."
  - text: "Life is short. Be the change you want to see in the world."

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "henryng24"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/sc-logo.png"
    date: "October 2015 - Present"
    description: "Helping build a brighter future"

# First image of the Timeline

timeline-img: "/img/author.png"

###########
# Contact #
###########

#email: ""

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Let me know your thoughts! And if you think this post would help someone, please share!"
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
#  - title: "facebook"
#    url: "https://facebook.com/"
  - title: "twitter"
    url: "https://twitter.com/henryng24"
#  - title: "github"
#    url: "https://github.com/henryng24"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/henryfcng"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#  - title: "rss"
#    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
